### PR TITLE
feat: fetch grammar from upstream

### PR DESCRIPTION
**Pull request by devanshj**
#2 [was already fixed on upstream](https://github.com/antlr/grammars-v4/pull/1787#issuecomment-657366339). So the grammars we have are stale. So wrote a script to fetch grammars from upstream and then build. We're using head.json to check if we're running behind from upstream.

So @urish could you please build, publish and then commit the head.json file. Thanks!

### CODE REVIEW

**Comment by urish** [comment]
Thank you @devanshj !

I'm actually not using this package anymore, and I don't have bandwidth to keep maintaining it. In case you are interested, please let me know...

**Comment by devanshj** [comment]
Oh okay I understand, this is gonna be the last thing this package would need after this PR everything is automated so if you could get this in it would be great! If you can't that's okay too no problems!

Also actually I was using this package but then went with a different approach altogether so neither am I actually using it haha. But this was the last thing required so I thought let's not keep things hanging. So to be clear neither am I up to maintain it.

**Comment by urish** [comment]
I hear you :)

What did you end up using?

**Comment by devanshj** [comment]
I was actually trying to parse the native java modules of React Native and generate TypeScript types so things are typesafe.

So
```java
@ReactMethod
void doFoo(String bar) {

}
```
would generate
```typescript
export const SomeModule = NativeModules.SomeModule as {
	doFoo: (bar: string) => void
}
```

I was trying it but the ast is too cumbersome. Then inspired from [this](https://github.com/vojtechhabarta/typescript-generator) I got the idea that I could simply use java's [reflection api](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/package-summary.html) to get the type information. I'll have to write some java for this but probably will be better than the ast approach.

**Comment by urish** [comment]
Yes, the reflection API sounds like the better way to go :)

**Comment by devanshj** [comment]
Yep! :D

**Comment by urish** [comment]
I looked at the code, it looks pretty neat! Any chance you could move from a chain of `then()` statement to using `await`?

**Comment by devanshj** [comment]
Thanks! I usually prefer `then` instead of `await` (I know I'm in the minority haha). The rational that I have for that is `await` gives a false promise of making the code look neat but it makes the code look less and less declarative.

Example I would prefer this:

```typescript
const getFiles = () =>
  Promise.all(
    files.map(file => 
      fetch(`https://raw.githubusercontent.com/antlr/grammars-v4/master/java/java/${file}`)
      .then(res => res.text())
      .then(data => ({ [file]: data }))
    )
  )
  .then(mergeAll)
```

instead of this:

```typescript
const getFiles = async () => {
  let filesMap = await Promise.all(
    files.map(async file => {
      let res = await fetch(`https://raw.githubusercontent.com/antlr/grammars-v4/master/java/java/${file}`)
      let data = await res.text();
      return { [file]: data };
    })
  )
  return mergeAll(filesMap)
}
```

async/await doesn't make anything better here imho instead adds too much reading overhead. Not only that but I'm big on [expressions over statements](https://fsharpforfunandprofit.com/posts/expressions-vs-statements/) (linking just in case you want to read why). So I don't like the introduction of redundant statements.

BUT all that being said I can still convert it to async/await if you strongly prefer that :)

PS: Just in case you also want to read [this](https://gist.github.com/devanshj/0c812eaa2c369c6d22eab959198a7412) (possibly over the top for some xD) old write-up (that I had in my notes until now haha) on why I like expressions (You might notice almost all functions I wrote here have only return in them)

**Comment by urish** [comment]
Thanks for explaining your viewpoint and providing specific examples :-)

Yes, I still prefer to use `async`/`await` in this case.

**Comment by devanshj** [comment]
Cool no problems! Refactored.

**Comment by devanshj** [comment]
Just a reminder: don't forget to build and publish (because the current grammars are stale) and then commit the head.json because that's what this PR is for :)

**Comment by urish** [comment]
Done, released as 0.3.0

Thanks again!

**Comment by devanshj** [comment]
You're welcome!

**Pull request merged**
